// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhkmYU5g6pfgyN5YAga8EAwfCT3Gq7Tko',
    appId: '1:518124281170:web:25e8bbe643dfcb084dee8b',
    messagingSenderId: '518124281170',
    projectId: 'noti-5e8b7',
    authDomain: 'noti-5e8b7.firebaseapp.com',
    storageBucket: 'noti-5e8b7.firebasestorage.app',
    measurementId: 'G-G06Y61KJ72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4U2FVOIamIu_ssU8E6tG6IkUSnL5HsKM',
    appId: '1:518124281170:android:8eddaf60131ea7294dee8b',
    messagingSenderId: '518124281170',
    projectId: 'noti-5e8b7',
    storageBucket: 'noti-5e8b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdjQFxZNMjd4D1VeaYwZ_S44ngVh9h9CE',
    appId: '1:518124281170:ios:6a59a78242d7e9ba4dee8b',
    messagingSenderId: '518124281170',
    projectId: 'noti-5e8b7',
    storageBucket: 'noti-5e8b7.firebasestorage.app',
    iosBundleId: 'com.example.smartCampusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdjQFxZNMjd4D1VeaYwZ_S44ngVh9h9CE',
    appId: '1:518124281170:ios:6a59a78242d7e9ba4dee8b',
    messagingSenderId: '518124281170',
    projectId: 'noti-5e8b7',
    storageBucket: 'noti-5e8b7.firebasestorage.app',
    iosBundleId: 'com.example.smartCampusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5iEJXBEWqYW7DnsS_RHNtoT700dHovd8',
    appId: '1:518124281170:web:6c7b7037d4c7135a4dee8b',
    messagingSenderId: '518124281170',
    projectId: 'noti-5e8b7',
    authDomain: 'noti-5e8b7.firebaseapp.com',
    storageBucket: 'noti-5e8b7.firebasestorage.app',
    measurementId: 'G-H3LL4HCNL2',
  );
}
